apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-standalone
  namespace: resilience
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
        selector: mongodb-standalone
    spec:
      containers:
      - name: mongodb-standalone
        image: mongo:latest
        command:
          - mongod
          - "--replSet"
          - rs0
          - "--dbpath"
          - "/tmp"
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: example
