---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: amq-streams
  namespace: resilience
spec:
  targetNamespaces:
  - resilience

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
  namespace: resilience
  labels:
    operators.coreos.com/amq-streams.resilience: ''
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  startingCSV: amqstreams.v2.0.0-0